PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fb: <http://rdf.freebase.com/ns/>
PREFIX local: <dataflow#>

SELECT DISTINCT ?area ?relatedArtwork
WHERE {
    GRAPH local:selected {
        local:global local:selectedArtwork ?selectedArtwork.
    }
#    SERVICE <http://146.148.9.150/sparql> {
        {} UNION {
            GRAPH <place.filters> {
                GRAPH <var.common> {
                    ?relatedArtwork
                        a fb:visual_art.artwork;
                        fb:common.topic.image/fb:type.content.source ?imageSource.
                    FILTER(?relatedArtwork != ?selectedArtwork).
                    FILTER(STRSTARTS(STR(?relatedArtwork),STR(fb:m))).
                }
            }
        }
#    }
}
ORDER BY ?area

